language: go
matrix:
  include:
  - go: 1.x
    env: LATEST=true
  - go: 1.10.x
  - go: 1.11.x
script:
- go vet
- go test -v ./...
- if [ "${LATEST}" = "true" ]; then GOOS=linux GOARCH=amd64 go build -ldflags "-X
  main.Version=`git rev-parse --short HEAD`" -o hero-file.linux.amd64 hero-file.go;
  fi
- if [ "${LATEST}" = "true" ]; then GOOS=darwin GOARCH=amd64 go build -ldflags "-X
  main.Version=`git rev-parse --short HEAD`" -o hero-file.darwin.amd64 hero-file.go;
  fi
- if [ "${LATEST}" = "true" ]; then GOOS=windows GOARCH=amd64 go build -ldflags "-X
  main.Version=`git rev-parse --short HEAD`" -o hero-file.windows.amd64.exe hero-file.go;
  fi
deploy:
  provider: releases
  api_key:
    secure: kYSujd2U/KCqMt9cQDz+pOotbEV2GR+TiMxVUiJxFJIkwax+HcEqJpYZAPwdYQrJk9REsWsIKu30i7V+bfcxaTR1ccT6An3KkDQWUxBtEkJFr61FelAcuKjes8mo3C8Dnigu8V9n7Ht29LyqAJEirwnNV2XSr0Xxp3s+hs98rKGW+IaUpqFLsDTpfJJ6eZNkHIKKtTUoe4kQiEmqS3RjF794kzDf/UbS5NGoNiIaTsEiMQUQivjBjKKlnoD1IcT90OY6WYDTTHRH4mJEdaaXtHwJBRvR67zD4xxaAibl+UBMzzS09Lj36AjJ31zfObxBt1f3/faOIttEX804ijE1ZJJevseufZud+6PTmeJPtwAhJsj4iRDM+d7CaOmvIqCCMKRbLB2kcXW+1e4t7gxjj6z9yQrvYnE+QJ1kvZwnuj32C+hdiD6uiLR0KG9sMa9ElJbwyumS0oeWPhc2rc4Us1DuCCjeqaV061VqRw2oQ0IjkEBNQM5eG86U5I0L8H7k+ZGHkvtcIfCV0Bx0FTNLZlv12grGkMdDSaBy5uZ0h4PLuo5wwRJ0lfAFMPCK9HcHnPK+909Dgz9IplAr6a5rCSH7r2GvCzIgRd/zu+ZYtrzXjmli/GnHXEXL7KV7j6j8O4w+P+s2uU+k7f5dwBgsqJAHPIco1ViDflwFYmaI7wY=
  file:
    - hero-file.linux.amd64
    - hero-file.darwin.amd64
    - hero-file.windows.amd64.exe
  on:
    repo: osallou/herodote-file
    tags: true
  skip_cleanup: 'true'
